"""Tests for the JSONL conversation parser."""

import os
import sys

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from unittest.mock import patch, MagicMock
from parser import parse_jsonl, clean_user_messages, _format_tool_use, _format_bash_result, _extract_user_text, _git_root

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "sample.jsonl")


def test_parse_session_metadata():
    session = parse_jsonl(FIXTURE)
    assert session.session_id == "test-session-abc123"
    assert session.slug == "fixing-login-bug"
    assert session.branch == "main"
    assert session.model == "claude-sonnet-4-5-20250514"
    assert session.project == "project"


def test_parse_user_messages():
    session = parse_jsonl(FIXTURE)
    # Should have 3 actual user messages (not tool_result-only entries)
    assert session.user_message_count == 3
    assert "Fix the login bug in auth.py" in session.user_messages[0]
    assert "empty strings" in session.user_messages[1]
    assert "Perfect" in session.user_messages[2]


def test_parse_files_touched():
    session = parse_jsonl(FIXTURE)
    assert "/Users/test/project/auth.py" in session.files_touched


def test_parse_tools_used():
    session = parse_jsonl(FIXTURE)
    assert "Edit" in session.tools_used
    assert "Read" in session.tools_used
    assert "Bash" in session.tools_used


def test_parse_timestamps():
    session = parse_jsonl(FIXTURE)
    assert session.started_at.startswith("2026-01-15")
    assert session.ended_at.startswith("2026-01-15")
    assert session.duration_seconds > 0


def test_parse_messages_list():
    session = parse_jsonl(FIXTURE)
    # Messages should alternate user/assistant, skipping tool-result-only entries
    assert len(session.messages) > 0
    roles = [m["role"] for m in session.messages]
    assert "user" in roles
    assert "assistant" in roles


def test_format_tool_use():
    assert _format_tool_use({"name": "Read", "input": {"file_path": "/foo/bar.py"}}) == "[Read /foo/bar.py]"
    assert _format_tool_use({"name": "Bash", "input": {"command": "ls -la"}}) == "[Bash: ls -la]"
    assert _format_tool_use({"name": "Grep", "input": {"pattern": "TODO"}}) == "[Grep: TODO]"
    assert _format_tool_use({"name": "Agent", "input": {"description": "research task"}}) == "[Agent: research task]"
    assert _format_tool_use({"name": "Skill", "input": {}}) == "[Skill]"


def test_format_bash_result_error():
    result = _format_bash_result("error line 1\nerror line 2", is_error=True)
    assert "error line 1" in result
    assert "error line 2" in result


def test_format_bash_result_short():
    result = _format_bash_result("ok", is_error=False)
    assert result == "ok"


def test_format_bash_result_long():
    lines = "\n".join(f"line {i}" for i in range(20))
    result = _format_bash_result(lines, is_error=False)
    assert "line 0" in result
    assert "line 1" in result
    assert "..." in result
    assert "line 19" in result


def test_extract_user_text_string():
    assert _extract_user_text("hello") == "hello"


def test_extract_user_text_array():
    content = [{"type": "text", "text": "hello"}, {"type": "tool_result", "content": "ignored"}]
    assert _extract_user_text(content) == "hello"


def test_parse_empty_file(tmp_path):
    empty = tmp_path / "empty.jsonl"
    empty.write_text("")
    session = parse_jsonl(str(empty))
    assert session.session_id == ""
    assert session.user_message_count == 0


def test_assistant_message_count():
    session = parse_jsonl(FIXTURE)
    # Sample fixture has assistant responses
    assert session.assistant_message_count > 0
    assert session.assistant_message_count == len(session.assistant_messages)


# ── clean_user_messages tests ────────────────────────────────────────────────

def test_clean_strips_command_tags():
    messages = [
        '<command-name>/exit</command-name>\n            <command-message>exit</command-message>\n            <command-args></command-args>',
    ]
    assert clean_user_messages(messages) == []


def test_clean_strips_local_command_noise():
    messages = [
        '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
        '<local-command-stdout>Goodbye!</local-command-stdout>',
    ]
    assert clean_user_messages(messages) == []


def test_clean_preserves_real_messages():
    messages = [
        "Fix the login bug in auth.py",
        "Also handle empty strings",
    ]
    assert clean_user_messages(messages) == messages


def test_clean_preserves_mixed_messages():
    """Messages with real text alongside command tags keep the real text."""
    messages = [
        '<command-name>/verify</command-name>\n<command-args>check all tests</command-args>\nPlease also review the error handling',
    ]
    result = clean_user_messages(messages)
    assert len(result) == 1
    assert "review the error handling" in result[0]


def test_clean_drops_noise_commands_as_plain_text():
    """Even without XML tags, bare /exit or /clear should be dropped."""
    messages = ["/exit", "/clear", "Fix the bug"]
    result = clean_user_messages(messages)
    assert result == ["Fix the bug"]


# ── _git_root worktree tests ────────────────────────────────────────────────

def _mock_git_root(toplevel: str) -> str:
    """Call _git_root with subprocess mocked to return the given toplevel."""
    mock_result = MagicMock(returncode=0, stdout=toplevel + "\n")
    with patch("parser.subprocess.run", return_value=mock_result):
        return _git_root("/dummy")


def test_git_root_worktree_resolves_to_parent():
    root = _mock_git_root("/Users/dev/dashboard-web/.claude-worktrees/feat-payout")
    assert root == "/Users/dev/dashboard-web"


def test_git_root_regular_project_unchanged():
    root = _mock_git_root("/Users/dev/dashboard-web")
    assert root == "/Users/dev/dashboard-web"
